name: Run Pre-commit Hooks and Gitlint

on:
  push:
    branches:
      - main  # Trigger on push to the main branch (or your default branch)
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  lint:
    runs-on: ubuntu-latest  # Runs on an Ubuntu environment

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install pre-commit and dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit gitlint yamllint hadolint

      - name: Install pre-commit hooks
        run: |
          pre-commit install

      # Step 5: Run pre-commit hooks
      - name: Run pre-commit hooks
        run: |
          pre-commit run --all-files

      # Step 6: Run gitlint for commit message linting
      - name: Run gitlint
        run: |
          gitlint

      # Step 7: Run yamllint (optional: if you want to lint YAML files)
      - name: Run yamllint
        run: |
          yamllint .

      # Step 8: Run Dockerfile lint (optional: if you want to lint Dockerfiles)
      - name: Run Dockerfile lint
        run: |
          hadolint Dockerfile
